### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Adel51** [l0b5ter/KeyDisplayed#1]
Hi,
I'm french.
I tried your module but i have problems.
Are you it works?
If yes, can u help me?
best regards

**Comment by l0b5ter** [comment]
Yess it works
But ofc I'll try to help you out^^
What is your problem?

**Comment by l0b5ter** [comment]
> Hi,
> I'm french.
> I tried your module but i have problems.
> Are you it works?
> If yes, can u help me?
> best regards

**Comment by Adel51** [comment]
hi,
it's written 'undefined'. When I clicked on a button on the keyboard, nothing happens!

**Comment by l0b5ter** [comment]
Seems like its an config issue, how does your config for the module look like?
It sud look similar to this (https://github.com/l0b5ter/KeyDisplayed/blob/master/KeyDisplayed/Readme.mk).
Where "url: [[113, "http://magicmirror.builders/"],"  decides which url sud open. "113" is the keycode and "http://magicmirror.builders/" is the link.

**Comment by l0b5ter** [comment]
Also i would assume that your using the (https://github.com/l0b5ter/iPress) to show the key pressed. 
This module only shows a number when you click a button on the keyboard.
Buttons on the mouse dont work

**Comment by l0b5ter** [comment]
Im gonna guess that the problem is solved.
However if you still have problem please reach out to me on discord (lobster#5273) or email (jostein.j.baustad@gmail.com)
